### ISSUE TITLE
Move links and header to nav

### ISSUE THREAD

**Issue by gregthompson27** [EthanLarios/EthanLarios.github.io#2]
https://github.com/EthanLarios/EthanLarios.github.io/blob/d7c73721f44d3f050de0e03cc43ed5433c253f51/portfolio.html#L20-L28

@EthanLarios, the code you have here on lines 20-28 should be inside of the `<nav>` tags that you have created above that currently only contain a comment. Move this code up into your nav section

**Comment by JoshHunter11** [comment]
@gregthompson27 issue resolved
